### ISSUE TITLE
Problema con la función client.get_static()

### ISSUE THREAD

**Issue by Juerodriguez** [manucabral/py-smn#3]
Buenas he tratado de ejecutar un script que usaba la funcion de get_static() y me sale el siguiente Traceback de error.

Traceback (most recent call last):
  File "/data/smn_national.py", line 21, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/data/smn_national.py", line 8, in main
    forecast_now = await client.get_static()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/envtest/lib/python3.11/site-packages/smn/client.py", line 66, in get_static
    tf_filename = await self.__get(SMNConstants.STATIC_ENDPOINT + 'tiepre', save=True, format='.zip')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/envtest/lib/python3.11/site-packages/smn/client.py", line 54, in __get
    return await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/envtest/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1166, in json

**Comment by manucabral** [comment]
Hola @Juerodriguez,
Gracias por reportar este error parece que han cambiado la respuesta del archivo estático. Pronto subo la nueva actualización. Mientras podes utilizar la primera opción "API".
